/**
 * Created by Abdallah on 4/25/2017.
 */

const Strings = {
    en: {
        translation: {
            LOGIN: "Login",
            LANGUAGE: "العربية",
            RESTAURANT: "Restaurant",
            FIND: "Find",
            SHOW_ALL: "Show all",
            DELIVERY: "Delivery",
            MIN: "Min",
            VIEW: "View",
            EDIT: "Edit",
            SUM: "Sum",
            TOTAL: "Total",
            MY_CART: "My Cart",
            CHECKOUT: "Checkout",
            FIRST_NAME: "First Name",
            LAST_NAME: "Last Name",
            PHONE_NUMBER: "Phone Number",
            EMAIL: "Email",
            AREA: "Area",
            STREET: "Street",
            BUILDING: "Building",
            APARTMENT: "Apartment",
            FLOOR: "Floor",
            ORDER: "Order",
            CUSTOMER_DETAILS: "Customer Details",
            SUBMIT_ORDER: "Submit Order",
            DELIVERY_TIME: "Delivery Time",
            ORDER_SUBMITTED: "Submitted order",
            OK: "Ok",
            SUCCESSFUL_ORDER_SUBMIT_MESSAGE_1: "Your order has been submitted to ",
            SUCCESSFUL_ORDER_SUBMIT_MESSAGE_2: ".\nYor order will arrive within the next ",
            MINUTES: "Minutes",
            ERROR_ITEMS_FROM_DIFFERENT_RESTAURANT: "You already have items from another restaurant in your cart," +
            " please checkout the current items or discard them before ordering from another restaurant.",
            PASSWORD: "Password",
            LOGIN_WRONG_CREDENTIALS_MESSAGE: "Wrong Username/password",
            LOGOUT: "Logout",
            GENERAL_SERVER_ERROR: "Oops, something wrong. Please try again",
            NAME: "Name",
            LOCATION: "Location",
            SHOW_ORDER: "Show Order",
            ACCEPT_ORDER: "Accept",
            ACCEPT_ORDER_ERROR: "Something went wrong, Couldn't accept this order.Please try again later",
            ORDER_ID: "Order ID",
            ADDRESS: "Address",
            ORDER_TIME: "Order Time",
            CUSTOMER_NAME: "Customer Name",
            STATUS: "Status",
            ACCEPTED: "Accepted",
            PENDING: "Pending",
            PICK_UP: "Pick Up",
            REQUIRED: "*Required",
            INVALID_DATA_MESSAGE: "The submitted fields contain invalid data, please correct them before submitting",
            NEW_ITEM: "New Item",
            EDIT_ITEM: "Edit Item",
            CANCEL: "Cancel",
            SAVE: "Save",
            ITEM_NAME: "Item Name",
            ITEM_DESCRIPTION: "Item Description",
            ITEM_PRICE: "Price",
            ERROR_TRY_AGAIN_LATER: "Error! something went wrong, please try again",
            SUCCESSFULL_EDIT_ITEM_MESSAGE: "Item has been updated successfully",
            TYPE: "Type",
            EMPTY_CART_MESSAGE: "Please add items to your cart to be able to submit order",
            USER_INVALID_MESSAGE: "You need to pass the verification test first",
            REMARKS: "Remarks",
            MAIN_PAGE_TEXT1: "Welcome to Foody Express",
            MAIN_PAGE_TEXT2: "Order Your Favourite Food Online Now",
            FOLLOW_US: "Follow us",
            ABOUT_US: "About us",
            ABOUT_US_MESSAGE: `Welcome to FoodyExpress... One of the best and  first websites for ordering your favourite food in Ramallah and Al-Bireh online.
            Just open the website, choose your cuisine and your restaurant among many others in Ramallah.
            No more waiting or calling. We are with you from the time you order till the food is in your hands.
            Know your delivery time before you order.`,
            ADD_RESTAURANT: "Add Restaurant",
            VIEW_RESTAURANTS: "View Restaurants",
            SUBSCRIBE_TO_OUR_NEWS_LETTER: "Subscribe to our newsletter",
            SUBSCRIBE_NOW: "Subscribe Now",
            SUBSCRIBED_SUCCESSFULLY: "Subscribed successfully",
            SUBSCRIBED_MESSAGE: "You have subscribed to our newsletter. From now on,you will get the latest offers",
            NEW_CATEGORY:"New Category",
            EDIT_ORDER:"Edit",
            CATEGORY_NAME:"Category Name"
        }
    }
    , ar: {
        translation: {
            LOGIN: "تسجيل الدخول",
            LANGUAGE: "English",
            RESTAURANT: "المطعم",
            FIND: "بحث",
            SHOW_ALL: "عرض الكل",
            DELIVERY: "التوصيل",
            Min: "حد أدنى",
            VIEW: "عرض",
            EDIT: "تعديل",
            SUM: "المجموع",
            TOTAL: "المجموع الكلي",
            MY_CART: "عربتي",
            CHECKOUT: "تنفيذ الطلب",
            FIRST_NAME: "الاسم الاول",
            LAST_NAME: "اسم العائلة",
            PHONE_NUMBER: "رقم الهاتف",
            EMAIL: "البريد الالكتروني",
            AREA: "المنطقة",
            STREET: "الشارع",
            BUILDING: "البناية",
            APARTMENT: "الشقة",
            FLOOR: "الطابق",
            ORDER: "الطلب",
            CUSTOMER_DETAILS: "معلومات المستخدم",
            SUBMIT_ORDER: "اطلب",
            DELIVERY_TIME: "فترة التوصيل",
            ORDER_SUBMITTED: "تم تقديم الطلب",
            OK: "حسنا",
            SUCCESSFUL_ORDER_SUBMIT_MESSAGE_1: "تم تقديم طلبك لمطعم ",
            SUCCESSFUL_ORDER_SUBMIT_MESSAGE_2: ".\nسيصل طلبك خلال ",
            MINUTES: "دقيقة",
            ERROR_ITEMS_FROM_DIFFERENT_RESTAURANT: "لديك طلبات من مطعم اخر حاليا, الرجاء القيام بتنفيذ الطلب الموجود حاليا او افراغ الطلبات قبل القيام بطلب اخر",
            PASSWORD: "كلمة المرور",
            LOGIN_WRONG_CREDENTIALS_MESSAGE: "اسم المتخدمظكلمة المرور غير صحيحة",
            ORDER: "اطلب",
            LOGOUT: "تسجيل الخروج",
            GENERAL_SERVER_ERROR: "خطأ, يرجى المحاولة مرة أخرى",
            NAME: "الاسم",
            LOCATION: "العنوان",
            SHOW_ORDER: "عرض الطلب",
            ACCEPT_ORDER: "قبول",
            ACCEPT_ORDER_ERROR: "خطأ في عملية قبول الطلب, الرجاء المحاولة مرة اخرى",
            ORDER_ID: "رقم الطلب",
            ADDRESS: "العنوان",
            ORDER_TIME: "وقت الطلب",
            CUSTOMER_NAME: "الاسم الكامل",
            STATUS: "الحالة",
            ACCEPTED: "تم القبول",
            PENDING: "غير مقبولة",
            PICK_UP: "بدون توصيل",
            REQUIRED: "*مطلوب",
            INVALID_DATA_MESSAGE: "المعلومات تحتوي بينات غير صحيحة, الرجاء التأكد منها قبل اؤسال الطلب",
            NEW_ORDER: "اضافة جديد",
            EDIT_ORDER: "تعديل",
            CANCEL: "الغاء",
            SAVE: "حفظ",
            ITEM_NAME: "الاسم",
            ITEM_DESCRIPTION: "الوصف",
            ITEM_PRICE: "السعر",
            ERROR_TRY_AGAIN_LATER: "خطأ, الرجاء المحاولة مرة أخرى",
            SUCCESSFULL_EDIT_ITEM_MESSAGE: "تم التعديل بنجاح",
            TYPE: "النوع",
            EMPTY_CART_MESSAGE: "الرجاء اضافة عناصر للتمكن من تقديم الطلب",
            USER_INVALID_MESSAGE: "يجب ان تنجح في الاثبات اولا",
            REMARKS: "تعليقات",
            MAIN_PAGE_TEXT1: "اهلا بك في فودي اكسبرس",
            MAIN_PAGE_TEXT2: "اطلب وجبتك المفضلة الان",
            FOLLOW_US: "تابعنا",
            ABOUT_US: "من نحن",
            ABOUT_US_MESSAGE: `اهلا في فودي اكسبرس... واحد من افضل واول المواقع لطلب طعامكم المفضل في رام الله والبيرة.
فقط افتح الموقع وقم باختيار وجبتك ومطعمك المفضل من عدة مطاعم في رام الله والبيرة. لا مزيد من الانتظار او الاتصال. نحن معك من لحظة الطلب الى ان يصل طلبكز اعرف وقت توصيل طلبك قبل ان تطلب!
`,
            ADD_RESTAURANT: "اضف مطعم",
            VIEW_RESTAURANTS: "عرض المطاعم",
            SUBSCRIBE_TO_OUR_NEWS_LETTER: "اشترك في نشرتنا الاخبارية",
            SUBSCRIBE_NOW: "اشترك الان",
            SUBSCRIBED_SUCCESSFULLY: "تم الاشتراك بنجاح ",
            SUBSCRIBED_MESSAGE: "لقد اشتركت في نشرتنا بنجاح,من الان فصاعدا ستصلك اخر العروضات",
            NEW_CATEGORY:"مجموعة جديدة",
            CATEGORY_NAME:"اسم المجموعة"
        }
    }
};

export default Strings;